In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_excel('multi_asset_etf_data.xlsx', sheet_name = "excess returns")

In [5]:
df.set_index('Date', inplace = True)
display(df)

,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SPY,TIP
Date,,,,,,,,,,,
2009-04-30,0.008440,-0.001553,0.155029,0.114637,0.137908,-0.028005,0.295598,0.229649,0.022329,0.098794,-0.018504
2009-05-31,0.054143,0.163134,0.159871,0.132389,0.029025,-0.020302,0.023198,0.054364,0.028336,0.058924,0.020438
2009-06-30,0.004550,-0.026858,-0.023094,-0.014648,0.032918,-0.006170,-0.025462,0.044850,-0.004035,-0.001254,0.001382
2009-07-31,0.031311,0.018595,0.110173,0.100442,0.069218,0.008345,0.105826,0.143274,0.015353,0.074633,0.000906
2009-08-31,0.007193,-0.040800,-0.013571,0.044596,-0.017404,0.007198,0.131503,0.032977,-0.004586,0.036505,0.007979
...,...,...,...,...,...,...,...,...,...,...,...
2022-01-31,-0.025361,0.079737,0.000610,-0.035535,-0.025734,-0.020315,-0.081499,-0.085213,-0.019946,-0.051926,-0.019773
2022-02-28,-0.010834,0.065037,-0.042840,-0.033929,-0.008228,-0.002679,-0.045518,-0.073240,-0.006383,-0.029154,0.008919
2022-03-31,-0.041877,0.092110,-0.033449,0.005552,-0.012509,-0.040247,0.069009,-0.007359,-0.002225,0.037953,-0.018393
2022-04-30,-0.069406,0.056699,-0.061061,-0.067101,-0.041513,-0.041992,-0.041014,-0.125388,-0.033108,-0.087479,-0.021540
2022-05-31,0.010315,0.052461,-0.008722,0.025143,0.024185,0.015864,-0.033610,0.012375,-0.003283,0.006978,-0.003782

## 2(1)(a) Summary statistics - mean and volatility of excess return

In [8]:
def stats(df):
    stats_df = (df.mean() * 12).to_frame('Mean')
    stats_df['Vol'] = df.std()*np.sqrt(12)
    stats_df['Sharpe'] = stats_df['Mean']/stats_df['Vol']
    
    return stats_df
    
summary_stats = stats(df)
display(summary_stats)

         Mean       Vol    Sharpe
BWX  0.006390  0.076505  0.083525
DBC  0.042225  0.181134  0.233116
EEM  0.073746  0.193170  0.381770
EFA  0.085370  0.160429  0.532138
HYG  0.072104  0.085733  0.841033
IEF  0.023507  0.058628  0.400955
IYR  0.151888  0.182766  0.831048
PSP  0.138939  0.217208  0.639657
QAI  0.020549  0.048389  0.424667
SPY  0.150734  0.142042  1.061189
TIP  0.032002  0.045452  0.704078

## 2(1)(b) Summary statistics - best and worst sharpe ratio

In [9]:
print("The asset with the highest/best Sharpe Ratio is", summary_stats['Sharpe'].idxmax(), summary_stats['Sharpe'].max())
print("The asset with the lowest/worst Sharpe Ratio is", summary_stats['Sharpe'].idxmin(), summary_stats['Sharpe'].min())

The asset with the highest/best Sharpe Ratio is SPY 1.0611888355674017
The asset with the lowest/worst Sharpe Ratio is BWX 0.08352526973785378

## 2(2)(a) Descriptive Analysis - Correlation matrix of returns

In [10]:
Corr_Matrix = df.corr()
display(Corr_Matrix)
Corr_Matrix[Corr_Matrix == 1] = None #Nullify values of 1

Pair_Max = Corr_Matrix.unstack().sort_values().dropna().index[-1]
Pair_Min = Corr_Matrix.unstack().sort_values().dropna().index[0]


print("The highest correlation is between", Pair_Max) #insert data here as well
print("\n")
print("The lowest correlation is between", Pair_Min)

,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SPY,TIP
BWX,1.000000,0.330982,0.609331,0.559939,0.507747,0.315212,0.388627,0.486088,0.624505,0.401463,0.551875
DBC,0.330982,1.000000,0.560808,0.580985,0.465019,-0.413355,0.285696,0.487789,0.535462,0.498145,0.075545
EEM,0.609331,0.560808,1.000000,0.851916,0.746547,-0.254467,0.604353,0.797594,0.801072,0.746713,0.233472
EFA,0.559939,0.580985,0.851916,1.000000,0.756339,-0.310853,0.671100,0.905540,0.834043,0.871234,0.160054
HYG,0.507747,0.465019,0.746547,0.756339,1.000000,-0.157887,0.738514,0.813852,0.750569,0.740805,0.235147
IEF,0.315212,-0.413355,-0.254467,-0.310853,-0.157887,1.000000,-0.059095,-0.301569,-0.085488,-0.328127,0.664207
IYR,0.388627,0.285696,0.604353,0.671100,0.738514,-0.059095,1.000000,0.737273,0.613673,0.730715,0.291943
PSP,0.486088,0.487789,0.797594,0.905540,0.813852,-0.301569,0.737273,1.000000,0.821420,0.898894,0.177978
QAI,0.624505,0.535462,0.801072,0.834043,0.750569,-0.085488,0.613673,0.821420,1.000000,0.828297,0.366972
SPY,0.401463,0.498145,0.746713,0.871234,0.740805,-0.328127,0.730715,0.898894,0.828297,1.000000,0.144071
TIP,0.551875,0.075545,0.233472,0.160054,0.235147,0.664207,0.291943,0.177978,0.366972,0.144071,1.000000

The highest correlation is between ('PSP', 'EFA')


The lowest correlation is between ('DBC', 'IEF')

## 2(2)(b) Descriptive Analysis - TIPS performance

In [11]:
summary_stats.loc[['TIP','IEF','BWX']]

         Mean       Vol    Sharpe
TIP  0.032002  0.045452  0.704078
IEF  0.023507  0.058628  0.400955
BWX  0.006390  0.076505  0.083525

In [12]:
print('It appears TIPS has higher average return than both domestic and international bonds. It also has lower volatility than the other two, which is ideal. Hence TIP has higher Sharpe Ratio than the other two.')

It appears TIPS has higher average return than both domestic and international bonds. It also has lower volatility than the other two, which is ideal. Hence TIP has higher Sharpe Ratio than the other two.

## 2(2)(c) Descriptibe Analysis - TIPS and investment opportunity set

In [13]:
print('Yes, Harvard should consider TIPS because it does not have high correlation with any other asset analysed above and has a relatively good performace and low risk. Hence, it makes a good asset to diversify risks of the portfolio.')

Yes, Harvard should consider TIPS because it does not have high correlation with any other asset analysed above and has a relatively good performace and low risk. Hence, it makes a good asset to diversify risks of the portfolio.

## 2(3)(a) The MV Frontier - tangency portfolio

In [14]:
def tangency_portfolio(df, diagonalize = False):
    sigma = df.cov() #sigma = covariance
    N = sigma.shape[0] #caculates number of assets
    sigma_adj = sigma.copy()
    if diagonalize:
        sigma_adj.loc[:,:] = np.diag(np.diag(sigma_adj)) #flip diagonally
    
    mu = df.mean()
    sigma_inv = np.linalg.inv(sigma_adj) #calculate inverse matrix of df
    weights = sigma_inv @ mu / (np.ones(N)@ sigma_inv @ mu)
    
    omega_tangency = pd.Series(weights, index=mu.index)
    return omega_tangency, mu, sigma_adj

omega_tangency, mu, sigma = tangency_portfolio(df)
omega_tangency.to_frame('Tangency Weights')

     Tangency Weights
BWX         -0.973072
DBC          0.191662
EEM          0.128369
EFA         -0.007233
HYG          1.308310
IEF          2.157144
IYR         -0.368802
PSP         -0.399092
QAI         -4.335348
SPY          2.348530
TIP          0.949532

## 2(3)(b) The MV Frontier - Compute mean, volatility, sharpe ratio

In [15]:
def portfolio_stats(omega, mu, sigma, annualize):
    mean = (mu @ omega) * annualize
    
    vol = np.sqrt(omega @ sigma @ omega) * np.sqrt(annualize)
    
    sharpe_ratio = mean/vol
    
    return round(pd.DataFrame(data = [mean, vol, sharpe_ratio], 
                              index = ['Mean','Volatility','Sharpe Ratio'],
                              columns = ['Portfolio stats']),4)

portfolio_stats(omega_tangency, mu, sigma, 12)

              Portfolio stats
Mean                   0.3396
Volatility             0.1653
Sharpe Ratio           2.0545

## 2(4)(a) Allocation - target return = 0.01

In [18]:
def target_portfolio(df, target_return = 0.01, diagonalize=False):
    omega_tangency, mu, sigma = tangency_portfolio(df, diagonalize = diagonalize)
    sigma_adj = sigma.copy()
    
    if diagonalize:
        sigma_adj.loc[:,:] = np,diag(np.diag(sigma_adj))
    sigma_inv = np.linalg.inv(sigma_adj)
    N = sigma_adj.shape[0]
    delta = ((np.ones(N) @ sigma_inv @ mu)/(mu @ sigma_inv @ mu)) * target_return
    omega_star = delta * omega
    
    return omega_star, mu, sigma_adj

omega_star, mu, sigma = target_portfolio(df)
omega_star_df = omega_star.to_frame('MV Portfolio Weights')
display(omega_star_df)

     MV Portfolio Weights
BWX             -0.343840
DBC              0.067725
EEM              0.045360
EFA             -0.002556
HYG              0.462298
IEF              0.762238
IYR             -0.130318
PSP             -0.141021
QAI             -1.531918
SPY              0.829865
TIP              0.335522

## 2(4)(b) Mean, volatility, sharpe ratio for above portfolio weights

In [19]:
portfolio_stats(omega_star, mu, sigma, 12)

              Portfolio stats
Mean                   0.1200
Volatility             0.0584
Sharpe Ratio           2.0545

## 2(4)(c) Long, short

In [20]:
omega_star_df.sort_values(omega_star_df.columns[0], ascending = False)

     MV Portfolio Weights
SPY              0.829865
IEF              0.762238
HYG              0.462298
TIP              0.335522
DBC              0.067725
EEM              0.045360
EFA             -0.002556
IYR             -0.130318
PSP             -0.141021
BWX             -0.343840
QAI             -1.531918

The portfolio with most long is SPY and most short is QAI. This portfolio has a large long position in SPY and large short position in QAI>

In [21]:
summary_stats.sort_values('Sharpe', ascending = False)

         Mean       Vol    Sharpe
SPY  0.150734  0.142042  1.061189
HYG  0.072104  0.085733  0.841033
IYR  0.151888  0.182766  0.831048
TIP  0.032002  0.045452  0.704078
PSP  0.138939  0.217208  0.639657
EFA  0.085370  0.160429  0.532138
QAI  0.020549  0.048389  0.424667
IEF  0.023507  0.058628  0.400955
EEM  0.073746  0.193170  0.381770
DBC  0.042225  0.181134  0.233116
BWX  0.006390  0.076505  0.083525

No, even though SPY does have the largest Sharpe ratio, QAI doesn't have the smallest Sharpe ratio.

## 2(5)(a) Simple portfolios - equally-weighted portfolio, target mean = 0.01

In [25]:
equal_weights = np.ones(len(omega_tangency))

target_mean = 0.01
equal_weights[equal_weights == 1] = (1/len(omega_tangency))

equal_weights = equal_weights * (target_mean / (df.mean()@ equal_weights))
portfolio_stats(equal_weights, mu, sigma, 12)

              Portfolio stats
Mean                   0.1200
Volatility             0.1626
Sharpe Ratio           0.7378

## 2(5)(b) Risk-parity

In [26]:
w = 1/(df.std())
target_mean = 0.01

factor = 1/((w@ df.mean()) / target_mean)

w = factor * w

w.to_frame('Weights')

      Weights
BWX  0.255745
DBC  0.108018
EEM  0.101288
EFA  0.121959
HYG  0.228217
IEF  0.333729
IYR  0.107053
PSP  0.090078
QAI  0.404340
SPY  0.137746
TIP  0.430472

In [27]:
portfolio_stats(w,mu,sigma,12)

              Portfolio stats
Mean                   0.1200
Volatility             0.1525
Sharpe Ratio           0.7867

## 2(5)(c) compare MV portfolio  to problem 2(4)

The Sharpe ratio from this portfolio is much lower than the one in 2(4). This portfolio doesn't have any short positions on any asset.

## 2(6)(a) Out-of-sample performance - compute weight for mu

In [32]:
df_2020 = df.loc[:'2020']
omega_p, mu_p, sigma_p = target_portfolio(df_2020, target_return=0.01, diagonalize=False)
omega_p.to_frame('MV Weights')

     MV Weights
BWX   -0.039015
DBC   -0.070835
EEM    0.027143
EFA   -0.076188
HYG    0.461422
IEF    0.844792
IYR   -0.209011
PSP   -0.024840
QAI   -1.197759
SPY    0.785427
TIP    0.056880

## 2(6)(b) Out-of-sample performance - Sharpe ratio 2021

In [34]:
omega_t2020, mu_tilde2020, Sigma2020 = tangency_portfolio(df_2020)

portfolio_stats(omega_p, mu_tilde2020, Sigma2020, 12)

              Portfolio stats
Mean                   0.1200
Volatility             0.0524
Sharpe Ratio           2.2899

## 2(6)(c) Out-of-sample performance - Sharpe ratio 2022

In [36]:
df_2021 = df.loc['2021':]

omega_t2021, mu_tilde2021, Sigma2021 = tangency_portfolio(df_2021)

portfolio_stats(omega_p, mu_tilde2021, Sigma2021, 12)

              Portfolio stats
Mean                  -0.0121
Volatility             0.0982
Sharpe Ratio          -0.1233